# Generated by Django 4.0 on 2021-12-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('week', models.IntegerField(default=52)),
            ],
            options={
                'ordering': ('-week',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avability', models.IntegerField(default=2)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_for', models.CharField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wendnesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default='Monday', max_length=15, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('meals', models.ManyToManyField(to='meal.Meal')),
                ('weekly_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.weeklymenu')),
            ],
            options={
                'ordering': ('created_for',),
            },
        ),
    ]
