# Generated by Django 4.0 on 2021-12-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_created_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_holiday',
        ),
    ]
