# Generated by Django 4.0 on 2021-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_weeklymenu_year_alter_weeklymenu_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymenu',
            name='week',
            field=models.IntegerField(default=52),
        ),
    ]
