# Generated by Django 4.0 on 2022-01-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_weeklymenu_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('weekly_menu', 'created_for')},
        ),
        migrations.AlterModelOptions(
            name='weeklymenu',
            options={'ordering': ('-year', '-week')},
        ),
        migrations.AlterField(
            model_name='weeklymenu',
            name='week',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='weeklymenu',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
