# Generated by Django 4.0.2 on 2022-02-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_options_alter_weeklymenu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymenu',
            name='week',
            field=models.IntegerField(default=6),
        ),
    ]
