# Generated by Django 4.0 on 2021-12-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_img',
            field=models.ImageField(blank=True, default='meal-default.png', null=True, upload_to=''),
        ),
    ]
