# Generated by Django 4.0 on 2021-12-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_category_name_alter_meal_meal_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
