# Generated by Django 4.0 on 2021-12-29 15:38

from django.db import migrations, models
import main.images_rename


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=main.images_rename.path_and_rename('')),
        ),
    ]
