# Generated by Django 4.0 on 2021-12-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_accepted_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='employee',
        ),
    ]
