# Generated by Django 4.0 on 2022-01-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_customer_order_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
    ]
